baseURL = "/"
languageCode = "en-us"
title = "Ez-Connect"
# summaryLength = 70

[taxonomies]
  tag = "tags"
  author = "authors"

[outputs]
  home = ["HTML", "ROBOTS", "Sitemap"]
  section = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = true
      taskLists = true
    # [markup.goldmark.parser]
    #   autoHeadingID = true
    #   autoHeadingIDType = "github"
    #   [markup.goldmark.parser.attribute]
    #     block = true
    #     title = true
    # [markup.goldmark.renderer]
    #   unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    # hl_Lines = ""
    # lineNoStart = 1
    # lineNos = true
    lineNumbersInTable = false
    # # noClasses = false
    # # Chroma Style Gallery: https://xyproto.github.io/splash/docs/
    # style = "dracula"
    # tabWidth = 4
