baseURL: /
title: Ez-Connect
summaryLength: 30

# https://gohugo.io/content-management/multilingual/#configure-languages
languageCode: en-us
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languages:
  en:
    languageName: EN
    dataDir: data/en # not work, use index $.Site.Data
    contentDir: content/en
  vi:
    languageName: VI
    dataDir: data/vi
    contentDir: content/vi

taxonomies:
  tag: tags

outputs:
  home: [HTML, ROBOTS, Sitemap]
  section: [HTML, JSON]

markup:
  goldmark:
    extensions:
      linkify: true
      taskLists: true
    # parser:
    #   autoHeadingID: true
    #   autoHeadingIDType: github
    #   attribute:
    #     block: true
    #     title: true
    # renderer:
    #   unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    # hl_Lines: ""
    # lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    # Chroma Style Gallery: https://xyproto.github.io/splash/docs/
    style: dracula
    tabWidth: 2

#
# Go module
#
# module:
#   imports:
#     path: github.com/kaushalmodi/hugo-debugprint
