baseURL: /
languageCode: en-us
title: Ez-Connect
# summaryLength = 70

taxonomies:
  tag: tags
  author: authors

outputs:
  home: [HTML, ROBOTS, Sitemap]
  section: [HTML, JSON]

markup:
  goldmark:
    extensions:
      linkify: true
      taskLists: true
    # parser:
    #   autoHeadingID: true
    #   autoHeadingIDType: github
    #   attribute:
    #     block: true
    #     title: true
    # renderer:
    #   unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    # hl_Lines: ""
    # lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    # Chroma Style Gallery: https://xyproto.github.io/splash/docs/
    style: dracula
    tabWidth: 2

module:
  imports:
    path: github.com/kaushalmodi/hugo-debugprint
