# Fallback to the default language
# The same value as `defaultContentLanguage`
defaultLanguage: en

# Enable or disable features to reduce the code size
options:
  # https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
  useSRI: true
  darkMode: false
  breadCrumb: true
  timeago: true
  mermaid: true
  plantUML: true
  quilljs: true
  flexSearch: true
