#
# Code generated by `gkgen`
#

.DEFAULT_GOAL := run
# GOPATH := $(shell go env GOPATH)

# Service
name := home

# Git
# gitBranch := $(shell git rev-parse --abbrev-ref HEAD)
# gitCommit := $(shell git rev-parse --short HEAD)

include .makerc
include .make.env

init:
	hugo mod get -u

syntax:
	@hugo gen chromastyles --style=dracula > assets/scss/components/_syntax.scss

lint:
	npm run lint

run:
	hugo serve --bind 0.0.0.0

build:
	rm -rf public
	hugo --gc --minify

# Share site via ngrok
share: build
	npm run http-server public/ &
	npm run ngrok authtoken 2760UjyRswx9WoJxA1WKbnw2t7Y_2MC5WfbCXHv787ggw93S7
	npm run ngrok http 8080

clean:
	git clean -fdx

helm:
	gkgen -k $(args) .
	helm lint chart

# K8s
# @buildah bud -t sample:0.0.1 args='--build-arg name=$(name) --build-arg version=$(VERSION)'

oci:
	buildah bud -t $(name):$(VERSION) $(args)

oci-push:
ifeq ($(and $(REGISTRY_USERNAME),$(REGISTRY_PWD)),)
	@echo 'User and password are incorrect'
	@exit 1
endif

	buildah login -u $(REGISTRY_USERNAME) -p $(REGISTRY_PWD) $(REGISTRY)
	buildah push $(name):$(VERSION) $(REGISTRY)/$(REGISTRY_REPO)/$(name):$(VERSION)

# Helm chart
package:
ifndef HELM_REPO
	@echo 'Missing "HELM_REPO" in .makerc'
	@exit 1
endif

	helm lint chart/
	helm cm-push chart/ $(HELM_REPO)

deploy:
	ssh $(SSH_DESTINATION) '$(HELM_CMD) install $(name) $(HELM_REPO)/$(name) -n $(NAMESPACE)'

deploy-delete:
	ssh $(SSH_DESTINATION) '$(HELM_CMD) uninstall $(name) $(HELM_REPO)/$(name) -n $(NAMESPACE)'
