#
# Code generated by `gkgen`
#

.DEFAULT_GOAL := run

# Service
name := hugo-theme
version := 0.2.0

# Git
gitBranch := $(shell git rev-parse --abbrev-ref HEAD)
gitCommit := $(shell git rev-parse --short HEAD)

-include .makerc

init:
	@hugo mod get -u

lint:
	@node_modules/.bin/stylelint assets/**/*.scss && eslint --ext assets/**/*.js

syntax:
	@hugo gen chromastyles --style=dracula > assets/scss/components/_syntax.scss

run:
	@hugo serve --bind 0.0.0.0

build:
	@rm -rf public/
	@hugo --gc --minify

clean:
	@git clean -fdx

helm:
	@gkgen -k $(args) .
	@helm lint chart

# K8s
oci:
	@buildah bud -t $(name):$(version) --build-arg name=$(name) --build-arg version=$(version)

ifneq ($(and $(REGISTRY_USERNAME),$(REGISTRY_PWD)),)
	@buildah login -u $(REGISTRY_USERNAME) -p $(REGISTRY_PWD) $(REGISTRY)
	buildah push $(name):$(version) $(REGISTRY)/$(REGISTRY_REPO)/$(name):$(version)
endif

# Helm chart
package:
	@helm cm-push chart/ hub-dev

deploy: package
	@ssh $(SSH_DESTINATION) '$(HELM_CMD) install $(name) hub-dev/$(name) -n dev'

deploy-delete: package
	@ssh $(SSH_DESTINATION) '$(HELM_CMD) uninstall $(name) hub-dev/$(name) -n dev'

deploy-restart:
	@ssh $(SSH_DESTINATION) '$(KUBECTL_CMD) rollout -n dev restart deploy/$(name)'

package-prod:
	@helm cm-push chart/ hub

deploy-prod: package-prod
	$(HELM_CMD) install $(name) hub-dev/$(name) -n prod
