name: hugo-theme
version: 0.2.2
description: Freemind home

port:
  http: 9000
  webhook: 8081

k8s:
  repository: docker.io/ezconnect/hugo-theme
  hostname: ez-connect.net
  service:
    http:
      host: home
    webhook:
      host: home-webhook
  tls: production-tls
  volume: {}
